-- Insert role metadata for all roles
INSERT INTO public.role_metadata (role, display_name, description, permissions, department_restricted) VALUES
('super_admin', 'Super Admin', 'Agency owner with full system access', '["*"]', false),
('ceo', 'Chief Executive Officer', 'Executive leadership and strategic oversight', '["view_all", "manage_executives", "view_reports"]', false),
('cto', 'Chief Technology Officer', 'Technology strategy and IT oversight', '["manage_tech", "view_projects", "manage_it"]', false),
('cfo', 'Chief Financial Officer', 'Financial strategy and oversight', '["manage_finance", "view_reports", "manage_budgets"]', false),
('coo', 'Chief Operations Officer', 'Operations strategy and management', '["manage_operations", "view_reports", "manage_departments"]', false),
('admin', 'Administrator', 'System administration and user management', '["manage_users", "view_reports", "manage_settings"]', false),
('operations_manager', 'Operations Manager', 'Day-to-day operations management', '["manage_operations", "view_team", "manage_processes"]', true),
('department_head', 'Department Head', 'Department leadership and management', '["manage_department", "view_team", "assign_tasks"]', true),
('team_lead', 'Team Lead', 'Team leadership and project coordination', '["manage_team", "create_projects", "assign_members"]', true),
('project_manager', 'Project Manager', 'Project planning and execution', '["manage_projects", "view_team", "track_progress"]', true),
('hr', 'Human Resources', 'Employee lifecycle and HR processes', '["manage_hr", "view_employees", "manage_leave"]', false),
('finance_manager', 'Finance Manager', 'Financial operations and reporting', '["manage_finance", "view_reports", "process_payments"]', false),
('sales_manager', 'Sales Manager', 'Sales operations and client management', '["manage_sales", "view_clients", "manage_leads"]', true),
('marketing_manager', 'Marketing Manager', 'Marketing campaigns and communications', '["manage_marketing", "view_analytics", "manage_content"]', true),
('quality_assurance', 'Quality Assurance', 'Quality control and compliance', '["manage_quality", "view_projects", "audit_processes"]', true),
('it_support', 'IT Support', 'Technical support and system maintenance', '["manage_it", "view_tickets", "system_admin"]', false),
('legal_counsel', 'Legal Counsel', 'Legal advice and compliance oversight', '["manage_legal", "view_contracts", "compliance_review"]', false),
('business_analyst', 'Business Analyst', 'Data analysis and business intelligence', '["view_analytics", "generate_reports", "analyze_data"]', true),
('customer_success', 'Customer Success', 'Client relationship and success management', '["manage_clients", "view_projects", "track_satisfaction"]', true),
('employee', 'Employee', 'General employee with standard access', '["view_own", "update_profile", "submit_requests"]', true),
('contractor', 'Contractor', 'Temporary contractor with limited access', '["view_assigned", "update_profile", "submit_timesheets"]', true),
('intern', 'Intern', 'Intern with supervised access', '["view_assigned", "update_profile", "submit_reports"]', true)
ON CONFLICT (role) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  permissions = EXCLUDED.permissions,
  department_restricted = EXCLUDED.department_restricted,
  updated_at = now();